# Generated by Django 4.0.4 on 2022-06-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('afeccion', models.CharField(max_length=20)),
                ('fecha_de_ingreso', models.DateField()),
                ('fecha_de_egreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='dados_de_baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('afeccion', models.CharField(max_length=20)),
                ('fecha_de_ingreso', models.DateField()),
                ('fecha_de_egreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='inofensivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('afeccion', models.CharField(max_length=20)),
                ('fecha_de_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='potencial_riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('afeccion', models.CharField(max_length=20)),
                ('fecha_de_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='riesgoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('afeccion', models.CharField(max_length=20)),
                ('fecha_de_ingreso', models.DateField()),
            ],
        ),
    ]
